//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseSet
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisLile
    {
        public int IdDisLake { get; set; }
        public Nullable<int> Post_id { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
